# Generated by Django 3.2.7 on 2021-09-09 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=500)),
                ('father_name', models.CharField(max_length=500)),
                ('customer_profile', models.CharField(max_length=500)),
                ('loan_account_number', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerHomeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=500)),
                ('address2', models.CharField(max_length=500)),
                ('address3', models.CharField(max_length=500)),
                ('landmark', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=500)),
                ('region_name', models.CharField(max_length=500)),
                ('area_name', models.CharField(max_length=500)),
                ('branch_name', models.CharField(max_length=500)),
                ('branch_code', models.CharField(max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.customer')),
            ],
        ),
    ]
