# Generated by Django 3.2.7 on 2021-09-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='area_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='region_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='zone_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_profile',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='father_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loan_account_number',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customerhomeaddress',
            name='address1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customerhomeaddress',
            name='address2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customerhomeaddress',
            name='address3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customerhomeaddress',
            name='landmark',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customerhomeaddress',
            name='pincode',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
